import Image from 'next/image';
import Link from 'next/link';
import Hero3D from '@/components/LazyHero3D';
import ScrollStory3D from '@/components/ScrollStory3D';
import ExpandingShowreel from '@/components/ExpandingShowreel';
import CultureRail from '@/components/CultureRail';
const services=[['01','Event Management','From first sketch to final guest — thoughtful planning and seamless production.','/images/private-dinner.png','/images/awards-concept.png'],['02','Public Relations','Stories, media moments and relationships that keep brands in the conversation.','/images/brand-launch.png','/images/private-dinner.png'],['03','Creative Direction','An ownable visual world that makes every touchpoint feel unmistakably yours.','/images/mehndi-concept.png','/images/brand-launch.png'],['04','Brand Experiences','Launches and activations designed to turn attention into real connection.','/images/awards-concept.png','/images/mehndi-concept.png']];
export default function Home(){return <>
  <section className="home-hero"><div className="hero-glow"/><Hero3D/><div className="hero-content"><span className="kicker"><b/>Independent creative agency · Pakistan</span><h1><span className="hero-line solid"><i>MAKE</i></span><span className="hero-line outline"><i>IT</i></span><span className="hero-line solid"><i>KULT.</i></span></h1><div className="hero-bottom"><p>We create high-impact events, PR moments and brand experiences built to move at the speed of culture.</p><Link className="button light-button" href="/work">View selected work <span>↗</span></Link></div></div><span className="side-note">Scroll to enter ↓</span><div className="hero-index">KULT® <i>01 — 25</i></div></section>
  <ExpandingShowreel/>
  <section className="statement"><span className="kicker">[ THE KULT EFFECT ]</span><div><p className="script">Attention is temporary. Impact isn’t.</p><h2>Experiences people <em>feel.</em><br/>Stories they <em>carry.</em></h2><div className="split-copy"><p>KULT is a creative events and PR agency translating strategy into unforgettable real-world moments across Pakistan.</p><Link href="/about">Who we are <span>↗</span></Link></div></div></section>
  <CultureRail/>
  <ScrollStory3D/>
  <section className="services-preview"><div className="section-heading"><span className="kicker">[ CAPABILITIES ]</span><h2>From signal<br/>to <em>spectacle.</em></h2></div><div className="capability-grid">{services.map(([n,t,d,img,alt])=><Link href="/services" key={n} className="capability-card" data-cursor><Image className="capability-primary" src={img} alt="" fill sizes="(max-width: 800px) 100vw, 50vw"/><Image className="capability-alt" src={alt} alt="" fill sizes="(max-width: 800px) 100vw, 50vw"/><div className="capability-shade"/><span>/{n}</span><b>↗</b><div><h3>{t}</h3><p>{d}</p></div></Link>)}</div></section>
  <section className="selected-work"><div className="section-heading"><span className="kicker">[ SELECTED WORLDS ]</span><h2>Work that<br/><em>changes the room.</em></h2></div><div className="project-grid"><Link href="/work" className="project large"><Image src="/images/brand-launch.png" alt="Contemporary beauty launch concept" fill sizes="(max-width: 800px) 100vw, 66vw"/><div><small>Brand launch · Karachi · 2026</small><h3>Attention / Activated</h3><span>Explore project ↗</span></div></Link><Link href="/work" className="project"><Image src="/images/private-dinner.png" alt="Private courtyard dinner concept" fill sizes="(max-width: 800px) 100vw, 34vw"/><div><small>Private experience · Lahore · 2026</small><h3>After / Hours</h3><span>Explore project ↗</span></div></Link></div><p className="concept-note">Original concept imagery — replace with approved KULT case studies before launch.</p></section>
  <section className="more-worlds"><div className="world"><Image src="/images/mehndi-concept.png" alt="Contemporary mehndi concept" fill sizes="50vw"/><div><small>CELEBRATION / LAHORE</small><h3>Colour / Uncontained</h3></div></div><div className="world"><Image src="/images/awards-concept.png" alt="Corporate awards experience concept" fill sizes="50vw"/><div><small>CORPORATE / KARACHI</small><h3>Future / Ceremony</h3></div></div></section>
  <section className="numbers"><span className="kicker">[ BUILT TO DELIVER ]</span><div><article><b>01</b><h3>One connected team</h3><p>Strategy, creative, PR and production aligned from day one.</p></article><article><b>360°</b><h3>End-to-end ownership</h3><p>One accountable partner from first call to final report.</p></article><article><b>∞</b><h3>Ideas without templates</h3><p>Every experience begins with the brief, never a package.</p></article></div></section>
  <section className="ticker"><span>Make noise. Make meaning. Make it KULT.</span></section>
  </>}
