'use client';
import {useEffect,useRef} from 'react';
import * as THREE from 'three';

export default function ScrollStory3D(){
 const root=useRef(null),mount=useRef(null);
 useEffect(()=>{
  const el=mount.current,section=root.current,articles=[...section.querySelectorAll('article')];
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,el.clientWidth/el.clientHeight,.1,100);camera.position.z=8.2;
  const renderer=new THREE.WebGLRenderer({alpha:true,antialias:innerWidth>700,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<800?1:1.2));renderer.setSize(el.clientWidth,el.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.55;el.appendChild(renderer.domElement);
  const rose=new THREE.MeshPhysicalMaterial({color:0xd77684,metalness:.35,roughness:.09,clearcoat:1,emissive:0x31070e,emissiveIntensity:.12});
  const mint=new THREE.MeshPhysicalMaterial({color:0x8edbd2,metalness:.16,roughness:.1,transmission:.2,thickness:1.7,clearcoat:1});
  const chrome=new THREE.MeshPhysicalMaterial({color:0xf1e8db,metalness:.9,roughness:.08,clearcoat:1});
  const group=new THREE.Group();scene.add(group);
  const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.48,3),mint);core.scale.set(1.05,.94,1.05);group.add(core);
  const nodes=new THREE.Group(),nodeData=[];for(let i=0;i<24;i++){const direction=new THREE.Vector3().randomDirection(),distance=1.85+(i%5)*.11,node=new THREE.Mesh(new THREE.SphereGeometry(i%5===0?.14:.065,18,18),i%5===0?rose:chrome);node.position.copy(direction).multiplyScalar(distance);nodeData.push({node,direction,distance});nodes.add(node)}group.add(nodes);
  const rings=[];for(let i=0;i<4;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(2.05+i*.15,.026+i*.007,12,140),i===2?rose:chrome);ring.rotation.set(.5+i*.43,.2+i*.28,.35-i*.2);rings.push(ring);group.add(ring)}
  const aura=new THREE.Mesh(new THREE.TorusGeometry(2.72,.012,8,150),rose);aura.rotation.set(1.1,.25,-.15);group.add(aura);
  scene.add(new THREE.HemisphereLight(0xf5fff9,0x173d34,3.4));const a=new THREE.PointLight(0xa3f5e9,58,18);a.position.set(4,4,5);scene.add(a);const b=new THREE.PointLight(0xff8498,48,18);b.position.set(-4,-2,5);scene.add(b);
  let progress=0,raf,scrollRaf,visible=true;
  const scroll=()=>{const rect=section.getBoundingClientRect();progress=Math.max(0,Math.min(1,-rect.top/Math.max(1,rect.height-innerHeight)));articles.forEach(article=>{const r=article.getBoundingClientRect(),center=r.top+r.height*.5,distance=Math.abs(center-innerHeight*.5),presence=Math.max(0,Math.min(1,1-distance/(innerHeight*.72))),inverse=1-presence;article.style.setProperty('--presence',presence.toFixed(3));article.style.setProperty('--story-opacity',(0.12+presence*.88).toFixed(3));article.style.setProperty('--shift-left',`${inverse*-150}px`);article.style.setProperty('--shift-right',`${inverse*170}px`);article.style.setProperty('--shift-up',`${inverse*120}px`);article.style.setProperty('--story-scale',(0.86+presence*.14).toFixed(3))})};
  const onScroll=()=>{if(scrollRaf)return;scrollRaf=requestAnimationFrame(()=>{scrollRaf=0;scroll()})};const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',resize);scroll();
  const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting},{rootMargin:'20% 0px'});observer.observe(section);const clock=new THREE.Clock();
  function draw(){if(visible){const t=clock.getElapsedTime(),stage=progress*2;let targetX;if(stage<=1)targetX=1.2-stage*2.35;else targetX=-1.15+(stage-1)*1.45;group.position.x+=(targetX-group.position.x)*.055;group.position.y=Math.sin(t*.45)*.08;group.rotation.y=t*.12+progress*1.25;group.rotation.x=Math.sin(t*.34)*.08;const pulse=1+Math.sin(progress*Math.PI*3)*.035;group.scale.setScalar(pulse);nodes.rotation.y=t*.16;nodeData.forEach(({node,direction,distance},i)=>node.position.copy(direction).multiplyScalar(distance+Math.sin(t*.8+i)*.045+progress*.18));rings.forEach((ring,i)=>ring.rotation.z+=.0007*(i+1)*(i%2?1:-1));aura.scale.setScalar(1+progress*.12);renderer.render(scene,camera)}raf=requestAnimationFrame(draw)}draw();
  return()=>{cancelAnimationFrame(raf);cancelAnimationFrame(scrollRaf);observer.disconnect();removeEventListener('scroll',onScroll);removeEventListener('resize',resize);group.traverse(object=>{object.geometry?.dispose()});rose.dispose();mint.dispose();chrome.dispose();renderer.dispose();el.removeChild(renderer.domElement)}
 },[]);
 return <section className="scroll-story cinematic-story" ref={root}><div className="story-sticky"><div className="story-atmosphere"/><div className="story-canvas" ref={mount}/><div className="story-label">KULT / METHOD <span>Scroll to shape the moment</span></div><div className="story-model-tag">One idea / continuously evolving</div></div><article className="enter-left"><span>01 / SIGNAL</span><h2>Find the<br/><em>reason.</em></h2><p>We decode the audience, ambition and cultural context before touching the aesthetics.</p></article><article className="enter-right"><span>02 / SHAPE</span><h2>Build the<br/><em>world.</em></h2><p>Strategy becomes a visual system, spatial journey and story guests can step inside.</p></article><article className="enter-behind"><span>03 / IMPACT</span><h2>Make it<br/><em>move.</em></h2><p>Production, PR and content work together so the experience travels beyond the room.</p></article></section>
}
