'use client';
import {useEffect,useRef} from 'react';
import * as THREE from 'three';

export default function ScrollStory3D(){
 const root=useRef(null),mount=useRef(null);
 useEffect(()=>{const el=mount.current,section=root.current,scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,el.clientWidth/el.clientHeight,.1,100);camera.position.z=7;
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(el.clientWidth,el.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;el.appendChild(renderer.domElement);
 const materials=[new THREE.MeshPhysicalMaterial({color:0xc76f7c,metalness:.25,roughness:.12,transmission:.16,clearcoat:1}),new THREE.MeshPhysicalMaterial({color:0x73bcb2,metalness:.35,roughness:.08,transmission:.35,thickness:1.5,wireframe:false,transparent:true}),new THREE.MeshPhysicalMaterial({color:0xe8ddd0,metalness:.92,roughness:.08,transparent:true})];
 const objects=[new THREE.Mesh(new THREE.TorusKnotGeometry(1.5,.42,150,24,2,3),materials[0]),new THREE.Mesh(new THREE.IcosahedronGeometry(1.85,4),materials[1]),new THREE.Group()];
 for(let i=0;i<7;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(.7+i*.18,.05,12,100),materials[2]);r.rotation.x=Math.PI/2;r.position.y=(i-3)*.34;objects[2].add(r)}objects.forEach((o,i)=>{o.visible=i===0;scene.add(o)});
 scene.add(new THREE.AmbientLight(0xe9f7f2,1.8));const a=new THREE.PointLight(0x8bd4ca,45,15);a.position.set(3,3,4);scene.add(a);const b=new THREE.PointLight(0xd27a86,35,15);b.position.set(-3,-2,4);scene.add(b);
 let progress=0,raf,isVisible=false;const scroll=()=>{const r=section.getBoundingClientRect();progress=Math.max(0,Math.min(1,-r.top/(r.height-innerHeight)))};const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',resize);scroll();
 const visibility=new IntersectionObserver(([entry])=>{isVisible=entry.isIntersecting},{rootMargin:'35% 0px'});visibility.observe(section);
 const clock=new THREE.Clock();function draw(){if(isVisible){const t=clock.getElapsedTime(),active=Math.min(2,Math.floor(progress*3));objects.forEach((o,i)=>{o.visible=i===active;if(o.visible){o.rotation.y=t*.22+progress*4;o.rotation.x=Math.sin(t*.45)*.18;o.position.y=Math.sin(t*.8)*.12;const s=.82+Math.sin(progress*Math.PI)*.2;o.scale.setScalar(s)}});renderer.render(scene,camera)}raf=requestAnimationFrame(draw)}draw();return()=>{cancelAnimationFrame(raf);visibility.disconnect();removeEventListener('scroll',scroll);removeEventListener('resize',resize);renderer.dispose();el.removeChild(renderer.domElement)}} ,[]);
 return <section className="scroll-story" ref={root}><div className="story-sticky"><div className="story-canvas" ref={mount}/><div className="story-label">KULT / METHOD <span>Scroll to shape the moment</span></div></div><article><span>01 / SIGNAL</span><h2>Find the<br/><em>reason.</em></h2><p>We decode the audience, ambition and cultural context before touching the aesthetics.</p></article><article><span>02 / SHAPE</span><h2>Build the<br/><em>world.</em></h2><p>Strategy becomes a visual system, spatial journey and story guests can step inside.</p></article><article><span>03 / IMPACT</span><h2>Make it<br/><em>move.</em></h2><p>Production, PR and content work together so the experience travels beyond the room.</p></article></section>
}
